branches:
  only:
    - master
notifications:
  slack:
    secure: wz2qegg1J0S9YFTglFkNM8gSfoJT1AviPZd3OTmp0gkwWrStOC6+eOltoXy7+blAlNaIu6dGo0nGqE6Eqf0oZvnVOyN9XKg4UoBEeFSeQTdpqygb35qiZmpiH1LNwWykFXVmfT5wodvLMBGcaATmmhdGzm0ViDyR4Wp8Txf9FyBiUMU4QC33dY2mxMYn70mFyJ/n1rWzeuqBb7utl8W45Bz3p1VFLtrIAAmh4WXFR/dvdsiK5FgyE1AulNHKGiOhmM6eClso7dr2ujoaP0jjnEiWeJi32ySlGexJjR/z4xKBW2EeTWzlyZf4xusYLXeYDt/ERHKsOhZWE93oBDhd1966/h3VAgxTJm9hfFrR1Ee99+JT1bjgXJDrBlJZthAELZ8p74/FNb3y+UA0ciuUCc2/zvMl/yNrUwcZkCKoCpk7hB2sOZsEFtwup6bphW0K8oiS05gw9k1um0OjLkVevw667+iTDrvCyxZxKd2Bv7yJRJHsAh1AcWwflqPjTAj2uLm6beG1JQTyUgT4vY84wfX0LEzVn2Bmr5OFXw5QEwXwRxX0sO2gnmgbUkbFu+0kWtxYx0O+Ga9pzST065uz1f2Cqk6n8UecLCi0ObSXSfdOK7WBNCjhW2W6/JV3lh09DZagJPOGZZZ2Uj/kX6ThO46vr0iBa67H+2zGRkthn9k=
language: python
python:
  - "3.7"
#  - "3.6.1"
#  - "3.7-dev" # 3.7 development branch
#  - "nightly" # currently points to 3.7-dev
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run httpbin locally and run tests. TODO: fix httpbin prod tests and openweathermap tests
script: gunicorn httpbin:app -D && py.test -k 'dev'
